app:
  builder_concurrency: 4  # Default: amount of CPUs
  max_glyphs: ~           # Max allowed glyphs per download. Unlimited if null.
  glyph_size:
    min: 12               # minimal size
    val: 16               # default size
    max: 30               # miximum size
  autoguess_charcode:
    min: 0xe800
    max: 0xf8ff
locales:
  enabled: [en]
  default: en
listen:
  host: localhost
  port: 3000
